name: compil/norm

on: [push, pull_request]

jobs:
  norminette:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: 'srcs includes libft'
